export const PROMOTION_STATUSES = [
  "DRAFT",
  "SCHEDULED",
  "ACTIVE",
  "PAUSED",
  "EXHAUSTED",
  "EXPIRED",
  "CANCELLED",
  "ARCHIVED",
] as const;

export const APPLICATION_MODES = [
  "AUTOMATIC",
  "CODE",
  "ADMIN_ASSIGNED",
  "TRIGGER_BASED",
] as const;

export const STACKING_POLICIES = [
  "NOT_STACKABLE",
  "CAN_COMBINE",
  "DISCOUNTS_EXCLUDED",
  "ACCOUNT_CREDITS_ALLOWED",
  "REFERRAL_REWARDS_ALLOWED",
  "BEST_DISCOUNT_WINS",
  "FIRST_APPLIED_WINS",
  "ADMIN_PRECEDENCE",
] as const;

export const PROMOTION_TYPES = [
  { id: "percentage_discount", category: "subscription_discount", label: "Percentage discount" },
  { id: "fixed_amount_discount", category: "subscription_discount", label: "Fixed amount discount" },
  { id: "first_month_discount", category: "subscription_discount", label: "First-month discount" },
  { id: "introductory_pricing", category: "subscription_discount", label: "Multi-month introductory pricing" },
  { id: "annual_plan_discount", category: "subscription_discount", label: "Annual-plan discount" },
  { id: "lifetime_discount", category: "subscription_discount", label: "Lifetime discount" },
  { id: "upgrade_discount", category: "subscription_discount", label: "Upgrade discount" },
  { id: "plan_specific_discount", category: "subscription_discount", label: "Plan-specific discount" },
  { id: "business_seat_discount", category: "subscription_discount", label: "Seat-based Business discount" },
  { id: "bundle_discount", category: "subscription_discount", label: "Bundle discount" },
  { id: "extended_free_trial", category: "free_access", label: "Extended free trial" },
  { id: "premium_trial", category: "free_access", label: "Premium trial" },
  { id: "feature_trial", category: "free_access", label: "Feature trial" },
  { id: "free_billing_period", category: "free_access", label: "Free billing period" },
  { id: "free_weekend", category: "free_access", label: "Free weekend" },
  { id: "launch_access", category: "free_access", label: "Launch access" },
  { id: "win_back_trial", category: "free_access", label: "Win-back trial" },
  { id: "business_pilot", category: "free_access", label: "Business pilot" },
  { id: "bonus_usage_credits", category: "usage_credit", label: "Usage and credit promotion" },
  { id: "referral_reward", category: "referral", label: "Referral promotion" },
  { id: "loyalty_reward", category: "loyalty_retention", label: "Loyalty and retention promotion" },
  { id: "conversion_offer", category: "conversion", label: "Conversion promotion" },
  { id: "retention_save_offer", category: "retention_winback", label: "Retention and win-back promotion" },
  { id: "seasonal_event_campaign", category: "seasonal_event", label: "Seasonal or event campaign" },
] as const;

export const REWARD_TYPES = [
  "PERCENTAGE_DISCOUNT",
  "FIXED_AMOUNT_DISCOUNT",
  "CUSTOM_INTRODUCTORY_PRICE",
  "FREE_TRIAL_DAYS",
  "FREE_SUBSCRIPTION_CYCLES",
  "PLAN_ACCESS",
  "FEATURE_ACCESS",
  "MODEL_ACCESS",
  "CHAT_MESSAGE_CREDITS",
  "THINKER_CREDITS",
  "DEEP_THINKER_CREDITS",
  "IMAGE_CREDITS",
  "API_CREDITS",
  "COMPUTE_CREDITS",
  "STORAGE_CREDITS",
  "DAILY_LIMIT_MULTIPLIER",
  "MONTHLY_LIMIT_MULTIPLIER",
  "QUALITY_UPGRADE",
  "BUSINESS_SEAT_CREDITS",
  "ACCOUNT_BALANCE_CREDIT",
  "LOYALTY_POINTS",
  "CUSTOM_REWARD",
] as const;

export const ELIGIBILITY_RULE_TYPES = [
  "ALL_USERS",
  "SPECIFIC_USERS",
  "EMAIL_DOMAIN",
  "PLAN",
  "FORMER_SUBSCRIBERS",
  "NEW_USERS",
  "COUNTRY",
  "STUDENTS",
  "DEVELOPERS",
  "CREATORS",
  "BUSINESS_CUSTOMERS",
  "ENTERPRISE_PROSPECTS",
  "BETA_TESTERS",
  "REFERRAL_USERS",
  "ACCOUNT_TAG",
  "FEATURE_USED",
  "FEATURE_NOT_USED",
  "USAGE_THRESHOLD",
  "REGISTERED_BEFORE",
  "REGISTERED_AFTER",
  "SUBSCRIPTION_EXPIRES_WITHIN",
  "NEVER_REDEEMED_PROMOTION",
  "ORGANIZATION",
  "ORGANIZATION_SEATS",
] as const;

export const LIMIT_TYPES = [
  "TOTAL_REDEMPTIONS",
  "PER_USER",
  "PER_HOUSEHOLD",
  "PER_PAYMENT_METHOD",
  "PER_ORGANIZATION",
  "DAILY_REDEMPTIONS",
  "FIRST_COME_FIRST_SERVED",
  "MAX_DISCOUNT_AMOUNT",
  "MAX_CREDIT_AMOUNT",
  "CAMPAIGN_BUDGET",
  "MAX_FINANCIAL_EXPOSURE",
] as const;

export const TRIGGER_EVENTS = [
  "USER_REGISTERED",
  "TRIAL_STARTED",
  "TRIAL_EXPIRED",
  "PLAN_LIMIT_WARNING_REACHED",
  "PLAN_LIMIT_REACHED",
  "SUBSCRIPTION_CREATED",
  "SUBSCRIPTION_CANCEL_REQUESTED",
  "SUBSCRIPTION_CANCELLED",
  "SUBSCRIPTION_RENEWED",
  "PAYMENT_FAILED",
  "USER_INACTIVE",
  "REFERRAL_COMPLETED",
  "USAGE_MILESTONE_REACHED",
  "BUSINESS_SEAT_THRESHOLD_REACHED",
  "MODEL_LAUNCHED",
] as const;

export const PRESENTATION_SURFACES = [
  "PRICING_PAGE_BANNER",
  "DASHBOARD_BANNER",
  "UPGRADE_MODAL",
  "CHECKOUT_MESSAGE",
  "EMAIL_NOTIFICATION",
  "IN_APP_NOTIFICATION",
  "BROWSER_NOTIFICATION",
  "PROMOTION_BADGE",
  "COUNTDOWN_TIMER",
  "CUSTOM_CALL_TO_ACTION",
  "CAMPAIGN_ARTWORK",
  "TERMS_LINK",
] as const;

export const ABUSE_CONTROLS = [
  "MULTI_ACCOUNT_SIGNUP",
  "RELATED_REFERRAL_ACCOUNTS",
  "EMAIL_ALIAS_REUSE",
  "IP_REDEMPTION_RATE",
  "PAYMENT_METHOD_REUSE",
  "PROMO_CODE_BRUTE_FORCE",
  "SELF_REFERRAL",
  "CANCEL_RESUBSCRIBE_LOOP",
  "ARTIFICIAL_BUSINESS_SEATS",
  "GRANT_BEFORE_PAYMENT_CONFIRMATION",
  "REFUND_AFTER_BENEFIT_CONSUMPTION",
] as const;

export const INITIAL_RELEASE_PROMOTIONS = [
  "Percentage subscription discount",
  "Fixed subscription discount",
  "Extended free trial",
  "First month free",
  "Temporary plan upgrade",
  "Bonus image credits",
  "Bonus Thinker and Deep Thinker credits",
  "Bonus storage",
  "API credit reward",
  "Referral reward",
  "First-upgrade promotion",
  "Cancellation save offer",
  "Cancelled-user win-back offer",
  "Business seat discount",
  "Admin-assigned custom promotion",
  "Promotion codes",
  "Automatic eligibility promotions",
  "Seasonal campaigns",
  "Beta tester and early-adopter rewards",
  "Multi-reward promotion bundles",
] as const;

export function promotionCatalog() {
  return {
    statuses: PROMOTION_STATUSES,
    applicationModes: APPLICATION_MODES,
    stackingPolicies: STACKING_POLICIES,
    promotionTypes: PROMOTION_TYPES,
    rewardTypes: REWARD_TYPES,
    eligibilityRuleTypes: ELIGIBILITY_RULE_TYPES,
    limitTypes: LIMIT_TYPES,
    triggerEvents: TRIGGER_EVENTS,
    presentationSurfaces: PRESENTATION_SURFACES,
    abuseControls: ABUSE_CONTROLS,
    initialReleasePromotions: INITIAL_RELEASE_PROMOTIONS,
  };
}
